import json

def balance_sentiment_data(input_file_path, output_file_path):
    """
    Balances the sentiment data to have a maximum of 100 positive entries
    and includes all negative, neutral, and off-topic entries.

    Args:
        input_file_path (str): The path to the input JSON file (e.g., from the previous script's output).
        output_file_path (str): The path where the balanced JSON data will be saved.
    """
    positive_entries = []
    neutral_entries = []
    other_sentiment_entries = []
    valid_labels = ["positive", "negative", "neutral", "offtopic"] # Define valid labels again for clarity

    try:
        with open(input_file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: Input file not found at {input_file_path}")
        return
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {input_file_path}. Check file format.")
        return

    for entry in data:
        sentiment = None
        if 'annotations' in entry and entry['annotations']:
            for annotation in entry['annotations']:
                if 'result' in annotation and annotation['result']:
                    for result_item in annotation['result']:
                        if 'value' in result_item and 'choices' in result_item['value']:
                            if result_item['from_name'] == 'sentiment' and result_item['value']['choices']:
                                sentiment = result_item['value']['choices'][0]
                                break
                if sentiment:
                    break

        if sentiment == "positive":
            positive_entries.append(entry)
        elif sentiment == "neutral":
            neutral_entries.append(entry)
        elif sentiment in ["negative", "offtopic"]:
            other_sentiment_entries.append(entry)

    # Take up to 100 positive entries
    selected_positive_entries = positive_entries[:70]
    selected_neutral_entries = neutral_entries[:100]

    # Combine the selected positive entries with all other sentiment entries
    balanced_data = selected_positive_entries + selected_neutral_entries + other_sentiment_entries

    try:
        with open(output_file_path, 'w', encoding='utf-8') as f:
            json.dump(balanced_data, f, indent=4)
        print(f"Balanced data saved to {output_file_path}")
        print(f"Total positive entries: {len(selected_positive_entries)}")
        print(f"Total other sentiment entries: {len(other_sentiment_entries)}")
        print(f"Total entries in new file: {len(balanced_data)}")
    except IOError:
        print(f"Error: Could not write to output file at {output_file_path}")

# --- How to use the script ---
# Make sure 'output_labelled_data.json' is the file generated by the previous script.
input_json_file = './scripts/output_labelled_data.json'
output_json_file = './exports/balanced_sentiment_data.json'

balance_sentiment_data(input_json_file, output_json_file)